return function(colors)
  return {
    -- Editor UI Elements
    Normal = { fg = colors.platinum, bg = colors.vampire_black },
    NormalNC = { fg = colors.platinum, bg = colors.vampire_black },
    CursorLine = { bg = colors.night_rider },
    CursorLineNr = { fg = colors.pastel_green, bold = true },
    LineNr = { fg = colors.outer_space },
    SignColumn = {},
    FoldColumn = {},
    ColorColumn = {},
    VertSplit = {},
    WinSeparator = {},
    Pmenu = {},
    PmenuSel = {},
    PmenuThumb = {},
    PmenuSbar = {},
    Search = {},
    IncSearch = {},
    MatchParen = {},
    StatusLine = { fg = colors.smokey_white, bg = colors.raisin_black, bold = true },
    StatusLineNC = {},
    TabLine = { fg = colors.platinum, bg = colors.raisin_black },
    TabLineSel = {},
    TabLineFill = {},
    Visual = { bg = colors.raisin_black },
    VisualNOS = {},
    Directory = {},
    WildMenu = {},

    -- Syntax Highlighting
    Comment = { fg = colors.outer_space, italic = true },
    String = { fg = colors.pastel_green },
    Character = {},
    Identifier = {},
    Function = { fg = colors.brandeis_blue, bold = true },
    Statement = {},
    Label = {},
    Conditional = {},
    Repeat = {},
    Operator = {},
    Exception = {},
    PreProc = {},
    Include = {},
    Define = {},
    Macro = {},
    StorageClass = {},
    Structure = {},
    Typedef = {},
    Special = {},
    SpecialChar = {},
    Tag = {},
    Delimiter = {},
    Debug = {},
    Underlined = {},
    Ignore = {},
    Error = { fg = colors.ruby_red, bold = true },

    -- Todo = {}.
    --Keyword = { fg = colors.dark_orchid, bold = true },
    Type = { fg = colors.wisteria },
    Variable = { fg = colors.platinum },
    Constant = { fg = colors.greenish_turquoise },

    -- Diagnostics & Errors
    Warning = { fg = colors.key_lime },
    WarningMsg = {},
    DiagnosticError = {},
    DiagnosticWarn = {},
    DiagnosticHint = {},
    DiagnosticInfo = {},

    Info = { fg = colors.light_aqua },
    Hint = { fg = colors.pale_cyan },
  }
end
